import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  useEffect(() => {
    // send browser route to iframe
    const browserRoute = localStorage.getItem('enterRoute')
    console.log(browserRoute, 'enterRouteenterRouteenterRoute');
    if(browserRoute) {
      localStorage.removeItem("enterRoute");
      window.history.pushState({}, null, browserRoute);
      
      setTimeout(() => {
        const el = document.getElementById('myIframe')
        if(el) {
          const message = JSON.stringify({
            browserRoute: browserRoute,
          });
          el.contentWindow.postMessage(message, '*')
        }
      }, 3000)
    }

    // recieve route form iframe
    window.addEventListener('message', function(e) {
      const data = typeof e.data === 'string' ? JSON.parse(e.data) : e.data;
      if(data.route) {
        console.log(data.route, 'route form iframe');
        window.history.pushState({}, null, data.route);
      }
    });
    
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <iframe id="myIframe" name="myIframe" src="http://localhost:3000" height="500px" width="1000px"></iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
